### ISSUE TITLE
REMOVE MODULE

### ISSUE THREAD

**Issue by corpsysgit** [mage2pro/mercadopago#3]
HOW TO REMOVE TOTALLY THE MODULE?

**Comment by corpsysgit** [comment]
1 exception(s):
Exception #0 (Magento\Framework\Exception\FileSystemException): The contents from the "/home/melbourne/public_html/vendor/mage2pro/mercadopago/etc/module.xml" file can't be read. Warning!file_get_contents(/home/melbourne/public_html/vendor/mage2pro/mercadopago/etc/module.xml): failed to open stream: No such file or directory

**Comment by dmitrii-fediuk** [comment]
All caps-lockers are banned here.
